name: Lint

on:
  push:
      branches:
        - chore/set-up-repository-pipeline-with-linter

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
