name: Lint

on: [push, pull_request]
branches:
  - chore/set-up-repository-pipeline-with-linter # todo: remove branch-specific after testing

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
