name: Lint
# TODO: remove branch-specfic rules when the main branch is lint-ready
on:
  push:
    branches:
      - chore/set-up-repository-pipeline-with-linter
  pull_request:
    branches:
      - chore/set-up-repository-pipeline-with-linter

jobs:
  code-formatter-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  linter-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
